apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-autogen-otel
spec:
  selector:
    matchLabels:
      name: python-autogen-otel
  template:
    metadata:
      labels:
        name: python-autogen-otel
    spec:
      containers:
      - name: python-autogen-otel
        image: docker.io/stevelerner/splk-python-autogen:latest
        ports:
        - containerPort: 6379
        env:
        - name: SPLUNK_SERVICE_NAME
          value: python-autogen-otel
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: SPLUNK_TRACE_EXPORTER_URL
          value: http://$(MY_NODE_NAME):9080/v1/trace
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: python-autogen-otel
spec:
  type: ClusterIP
  selector:
    app: python-autogen-otel
  ports:
  - name: redis
    port: 6379
    targetPort: 6379