FROM python:slim
RUN apt-get update && \ 
    apt install -y python3-pip && \
    apt install -y procps && \
    apt install -y net-tools && \
    apt install -y curl && \
    apt install -y netcat && \
    apt install -y vim && \
    python3 -m pip install requests && \
    apt -y autoremove && apt-get -y autoclean && \
    export PATH="$HOME/.local/bin:$PATH" && \
    splk-py-trace-bootstrap  && \
    mkdir /home/code
WORKDIR /home/code
COPY . /home/code/