FROM python:slim
RUN apt-get update && \ 
    apt -y autoremove && apt-get -y autoclean && \
    mkdir /home/code
ENV PYTHONUNBUFFERED definitely
WORKDIR /home/code
COPY . /home/code/
CMD ["/bin/sh", "run-print.sh"]