apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-print-otel
spec:
  selector:
    matchLabels:
      name: python-print-otel
  template:
    metadata:
      labels:
        name: python-print-otel
    spec:
      containers:
      - name: python-print-otel
        image: docker.io/stevelerner/python-print:latest
        env:
        - name: PYTHONIOENCODING
          value: "utf-8"
        - name: PYTHONUNBUFFERED=0
          value: "0"
        command: ["/bin/sh"]
        args: ["run-print.sh"]
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: python-print-otel
spec:
  type: ClusterIP
  selector:
    app: python-print-otel