apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-python-print-otel
spec:
  selector:
    matchLabels:
      name: test-python-print-otel
  template:
    metadata:
      labels:
        name: test-python-print-otel
    spec:
      containers:
      - name: test-python-print-otel
        image: docker.io/stevelerner/python-print:latest
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONIOENCODING
          value: "utf-8"
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: test-python-print-otel
spec:
  type: ClusterIP
  selector:
    app: test-python-print-otel